name: "diff-check"

on: [ push,pull_request ]

jobs:
  diff-check:
    name: diff-check
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Git Diff
        run: if [ "$(git diff | wc -l)" -gt 0 ]; then exit 1; fi
